### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by archermarx** [UM-PEPL/HallThruster.jl#40]
- [x] Anode sheath model
- [x] Anode sheath heat flux
- [ ] Easy running of LANDMARK cases
- [x] Compute current at left boundary as well
- [x] Better restarts
    - [x] Tests for restarts
    - [x] Interpolate restarts
    - [x] Restarts that load consistently
- [x] Better initialization
- [x] Extra loss term in energy equation (1/2 me ue^2 term)
- [ ] Freestream preservation test
- [ ] End-to-end OVS test
- [x] Get 2nd order working properly for heavy species
- [x] Comparisons to Hall2De and HALLIS
- [x] Documentation
    - [x] Intro page
    - [x] LANDMARK comparisons 
    - [x] Ionization, collision, excitation models
    - [x] Anomalous transport models
    - [x] Tutorial
    - [x] Configuration
    - [x] Physics model
    - [x] Fluxes and numerics
    - [x] Initialization
    - [x] source terms
    - [x] wall loss models
    - [x] thrusters
    - [x] Contribution
    - [x] Citation
    - [x] Background on Hall thrusters
- [x] JOSS writup
- [x] Excitation reactions
- [x] Krypton
    - [x] Ionization
    - [x] Ionization losses
    - [x] Wall/sheath losses
- [x] Multiply-charged ions
- [x] Track down non-repeatability with SSPRK
- [x] Background pressure effects
- [x] Move plotting to recipes
- [x] first release
- [x] Registration
- [x] Easier post-processing
- [ ] Makie plotting?
- [x] Reduce precompile time
- [x] Get data-driven models working (smooth derivative operators may help)
- [x] Efficiency computation (including energy/momentum/mass lost in radial direction)
- [ ] Conservation checks
- [x] Radial ion losses
- [x] More tutorials
- [x] JSON stuff
    - [X] Input
    - [X] Output
    - [x] Performance metrics for JANUS
    - [x] Tests to make sure it works properly
- [x] New electron excitation model following Dugan and Sovie, Fife, Park
- [x] Better wall loss model
- [ ] OVS to verify order of time integration
- [x] Revise JOSS paper
- [ ] Add time integration documentation
- [ ] Hybrid-PIC module (PIC ions)
- [ ] Fast stationary model (e.g. Ahedo http://nanoelsim.hvt.bme.hu/res/Hall/cikk/1.1371519.pdf or Garrigues)
- [x] Quasi-1D flow (again see Ahedo)
- [x] Better documentation of available anomalous transport models
- [X] More robust electron solve

**Comment by dere4** [comment]
compute current at left boundary done. 

- add FFT to get PSD from discharge currents in postprocessing.jl, also return limits in resolution due to length of time series and saving interval

**Comment by dere4** [comment]
for Krypton point:
generalize energy loss to walls
